---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: component-harbor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.19.2
    helm:
      valuesObject:
        expose:
          tls:
            certSource: secret
            secret:
              secretName: harbor-tls
          ingress:
            hosts:
              core: harbor.internal.donaldsebleung.com
            annotations:
              cluster-name: donaldsebleung-nucbox-k11
        externalURL: https://harbor.internal.donaldsebleung.com
        metrics:
          enabled: true
          serviceMonitor:
            enabled: true
        core:
          extraEnvVars:
            - name: REGISTRY_HTTP_CLIENT_TIMEOUT
              value: '1440'
        jobservice:
          registryHttpClientTimeout: 1440
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
