---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
    argocd.argoproj.io/sync-options: 'Wait=true'
  name: harbor-tls
  namespace: harbor
spec:
  secretName: harbor-tls
  duration: 8760h
  renewBefore: 720h
  issuerRef:
    name: root-ca-clusterissuer
    kind: ClusterIssuer
  commonName: harbor.internal.donaldsebleung.com
  dnsNames:
    - harbor.internal.donaldsebleung.com
