---
apiVersion: argoproj.io/v1beta1
kind: ArgoCD
metadata:
  annotations:
    argocd.argoproj.io/sync-options: 'ServerSideApply=true,Validate=false'
  name: argocd
spec:
  server:
    host: argocd.internal.donaldsebleung.com
    ingress:
      annotations:
        cluster-name: donaldsebleung-nucbox-k11
      enabled: true
      tls:
        - hosts:
            - argocd.internal.donaldsebleung.com
          secretName: argocd-tls
