---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: component-jupyterhub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://hub.jupyter.org/helm-chart/
    chart: jupyterhub
    targetRevision: 4.4.0
    helm:
      valuesObject:
        ingress:
          enabled: true
          annotations:
            cluster-name: donaldsebleung-nucbox-k11
          hosts:
            - jupyterhub.internal.donaldsebleung.com
          tls:
            - hosts:
                - jupyterhub.internal.donaldsebleung.com
              secretName: jupyterhub-tls
        proxy:
          service:
            type: ClusterIP
        singleuser:
          networkPolicy:
            egressAllowRules:
              privateIPs: true
          extraEnv:
            MLFLOW_TRACKING_URI: "http://component-mlflow-mlflow.mlflow:5000"
          profileList:
            - display_name: "MindSpore 2.10.0 - cpu.small"
              description: "MindSpore 2.10.0 on CPU platform with 2 vCPU and 8G memory"
              default: true
              kubespawner_override:
                image: "harbor.internal.donaldsebleung.com/jupyter/mindspore-notebook:mindspore-2.10.0.post1"
                cpu_guarantee: 2.0
                cpu_limit: 2.0
                mem_guarantee: "8G"
                mem_limit: "8G"
            - display_name: "MindSpore 2.10.0 - cpu.medium"
              description: "MindSpore 2.10.0 on CPU platform with 4 vCPU and 16G memory"
              kubespawner_override:
                image: "harbor.internal.donaldsebleung.com/jupyter/mindspore-notebook:mindspore-2.10.0.post1"
                cpu_guarantee: 4.0
                cpu_limit: 4.0
                mem_guarantee: "16G"
                mem_limit: "16G"
            - display_name: "MindSpore 2.10.0 - cpu.large"
              description: "MindSpore 2.10.0 on CPU platform with 8 vCPU and 32G memory"
              kubespawner_override:
                image: "harbor.internal.donaldsebleung.com/jupyter/mindspore-notebook:mindspore-2.10.0.post1"
                cpu_guarantee: 8.0
                cpu_limit: 8.0
                mem_guarantee: "32G"
                mem_limit: "32G"
            - display_name: "MindSpore 2.10.0 + CANN 8.5.0 - npu.0.small"
              description: "MindSpore 2.10.0 + CANN 8.5.0 on Ascend platform with 2 vCPU, 8G memory and Ascend 310P NPU #0"
              kubespawner_override:
                image: "harbor.internal.donaldsebleung.com/jupyter/mindspore-notebook:cann8.5.0-mindspore-2.10.0.post1"
                extra_pod_config:
                  runtimeClassName: 'ascend'
                environment:
                  ASCEND_VISIBLE_DEVICES: '0'
                  LD_LIBRARY_PATH: '/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/dcmi:/usr/local/Ascend/driver/lib64/driver'
                cpu_guarantee: 2.0
                cpu_limit: 2.0
                mem_guarantee: "8G"
                mem_limit: "8G"
            - display_name: "MindSpore 2.10.0 + CANN 8.5.0 - npu.1.small"
              description: "MindSpore 2.10.0 + CANN 8.5.0 on Ascend platform with 2 vCPU, 8G memory and Ascend 310P NPU #1"
              kubespawner_override:
                image: "harbor.internal.donaldsebleung.com/jupyter/mindspore-notebook:cann8.5.0-mindspore-2.10.0.post1"
                extra_pod_config:
                  runtimeClassName: 'ascend'
                environment:
                  ASCEND_VISIBLE_DEVICES: '1'
                  LD_LIBRARY_PATH: '/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/dcmi:/usr/local/Ascend/driver/lib64/driver'
                cpu_guarantee: 2.0
                cpu_limit: 2.0
                mem_guarantee: "8G"
                mem_limit: "8G"
            - display_name: "MindSpore 2.10.0 + CANN 8.5.0 - npu.0.medium"
              description: "MindSpore 2.10.0 + CANN 8.5.0 on Ascend platform with 4 vCPU, 16G memory and Ascend 310P NPU #0"
              kubespawner_override:
                image: "harbor.internal.donaldsebleung.com/jupyter/mindspore-notebook:cann8.5.0-mindspore-2.10.0.post1"
                extra_pod_config:
                  runtimeClassName: 'ascend'
                environment:
                  ASCEND_VISIBLE_DEVICES: '0'
                  LD_LIBRARY_PATH: '/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/dcmi:/usr/local/Ascend/driver/lib64/driver'
                cpu_guarantee: 4.0
                cpu_limit: 4.0
                mem_guarantee: "16G"
                mem_limit: "16G"
            - display_name: "MindSpore 2.10.0 + CANN 8.5.0 - npu.1.medium"
              description: "MindSpore 2.10.0 + CANN 8.5.0 on Ascend platform with 4 vCPU, 16G memory and Ascend 310P NPU #1"
              kubespawner_override:
                image: "harbor.internal.donaldsebleung.com/jupyter/mindspore-notebook:cann8.5.0-mindspore-2.10.0.post1"
                extra_pod_config:
                  runtimeClassName: 'ascend'
                environment:
                  ASCEND_VISIBLE_DEVICES: '1'
                  LD_LIBRARY_PATH: '/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/dcmi:/usr/local/Ascend/driver/lib64/driver'
                cpu_guarantee: 4.0
                cpu_limit: 4.0
                mem_guarantee: "16G"
                mem_limit: "16G"
            - display_name: "MindSpore 2.10.0 + CANN 8.5.0 - npu.0.large"
              description: "MindSpore 2.10.0 + CANN 8.5.0 on Ascend platform with 8 vCPU, 32G memory and Ascend 310P NPU #0"
              kubespawner_override:
                image: "harbor.internal.donaldsebleung.com/jupyter/mindspore-notebook:cann8.5.0-mindspore-2.10.0.post1"
                extra_pod_config:
                  runtimeClassName: 'ascend'
                environment:
                  ASCEND_VISIBLE_DEVICES: '0'
                  LD_LIBRARY_PATH: '/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/dcmi:/usr/local/Ascend/driver/lib64/driver'
                cpu_guarantee: 8.0
                cpu_limit: 8.0
                mem_guarantee: "32G"
                mem_limit: "32G"
            - display_name: "MindSpore 2.10.0 + CANN 8.5.0 - npu.1.large"
              description: "MindSpore 2.10.0 + CANN 8.5.0 on Ascend platform with 8 vCPU, 32G memory and Ascend 310P NPU #1"
              kubespawner_override:
                image: "harbor.internal.donaldsebleung.com/jupyter/mindspore-notebook:cann8.5.0-mindspore-2.10.0.post1"
                extra_pod_config:
                  runtimeClassName: 'ascend'
                environment:
                  ASCEND_VISIBLE_DEVICES: '1'
                  LD_LIBRARY_PATH: '/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/dcmi:/usr/local/Ascend/driver/lib64/driver'
                cpu_guarantee: 8.0
                cpu_limit: 8.0
                mem_guarantee: "32G"
                mem_limit: "32G"
            - display_name: "MindSpore 2.10.0 + CANN 8.5.0 - npu.xlarge"
              description: "MindSpore 2.10.0 + CANN 8.5.0 on Ascend platform with 8 vCPU, 64G memory and 2x Ascend 310P NPU"
              kubespawner_override:
                image: "harbor.internal.donaldsebleung.com/jupyter/mindspore-notebook:cann8.5.0-mindspore-2.10.0.post1"
                extra_pod_config:
                  runtimeClassName: 'ascend'
                environment:
                  ASCEND_VISIBLE_DEVICES: '0-1'
                  LD_LIBRARY_PATH: '/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/dcmi:/usr/local/Ascend/driver/lib64/driver'
                cpu_guarantee: 8.0
                cpu_limit: 8.0
                mem_guarantee: "64G"
                mem_limit: "64G"
  destination:
    server: https://kubernetes.default.svc
    namespace: jupyterhub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
