---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
    argocd.argoproj.io/sync-options: 'Wait=true'
  name: jupyterhub-tls
  namespace: jupyterhub
spec:
  secretName: jupyterhub-tls
  duration: 8760h
  renewBefore: 720h
  issuerRef:
    name: root-ca-clusterissuer
    kind: ClusterIssuer
  commonName: jupyterhub.internal.donaldsebleung.com
  dnsNames:
    - jupyterhub.internal.donaldsebleung.com
